import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import fs from 'fs/promises';
import { Layout } from 'components/Layout';

export default function Home({ latestComics }) {
  return (
    <>
      <Head>
        <title>xkdc - Comics for developers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h2 className="text-3xl font-bold text-center mb-10">Latest comics</h2>

        <section className="grid grid-cols-1 gap-2 max-w-md m-auto sm:grid-cols-2 md:grid-cols-3">
          {latestComics.map((comic) => {
            return (
              <Link key={comic.id} href={`/comic/${comic.id}`}>
                <a className="mb-4 pb-4 m-auto">
                  <h3 className="font-bold text-sm text-center pb-2">{comic.title}</h3>

                  <Image src={comic.img} alt={comic.alt} width={comic.width} height={comic.height} />
                </a>
              </Link>
            );
          })}
        </section>
      </Layout>
    </>
  );
}

export async function getStaticProps(context) {
  // Leer los archivos Json en comics
  const files = await fs.readdir('./comics');
  // Obtener los nombres de los archivos
  const lastestComicsFiles = files.slice(-8, files.length);

  // Leer el contenido de los archivos
  const promisesReadFiles = lastestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, 'utf8');

    return JSON.parse(content);
  });

  const latestComics = await Promise.all(promisesReadFiles);

  return {
    props: {
      latestComics,
    },
  };
}
