import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Container, Card, Row, Text } from "@nextui-org/react";
import { Header } from "../components/Header";

import fs from "fs/promises";
import Link from "next/link";
import Image from "next/image";

// {
//     id: 2587,
//     img: 'https://imgs.xkcd.com/comics/for_the_sake_of_simplicity.png',
//     height: 497,
//     width: 322,
//     month: '2',
//     link: '',
//     year: '2022',
//     safe_title: 'For the Sake of Simplicity',
//     alt: 'For the sake of simplicity, gardeners are assumed to move through Euclidean space--neglecting the distortion from general relativity--unless they are in the vicinity of a Schwarzschild Orchid.',
//     title: 'For the Sake of Simplicity',
//     day: '28'
//   }

export default function Home({ latestComics }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h2 className="text-3xl font-bold text-center mb-10">Latest comics</h2>

        <section className="grid grid-cols-1 gap-2 max-w-md m-auto sm:grid-cols-2 md:grid-cols-3">
          {latestComics.map((comic) => {
            return (
              <Link key={comic.id} href={`/comic/${comic.id}`}>
                <a className="mb-4 pb-4 m-auto">
                  <h3 className="font-bold text-sm text-center pb-2">
                    {comic.title}
                  </h3>

                  <Image
                    src={comic.img}
                    alt={comic.alt}
                    width={300}
                    height={300}
                    layout="intrinsic"
                    objectFit="contain"
                  />
                </a>
              </Link>
            );
          })}
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  // Leer los archivos Json en comics
  const files = await fs.readdir("./comics");
  // Obtener los nombres de los archivos
  const lastestComicsFiles = files.slice(-8, files.length);

  // Leer el contenido de los archivos
  const promisesReadFiles = lastestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, "utf8");

    return JSON.parse(content);
  });

  const latestComics = await Promise.all(promisesReadFiles);

  return {
    props: {
      latestComics,
    },
  };
}
